### ISSUE TITLE
<Formik ... > instead of useFormik()

### ISSUE THREAD

**Issue by purplestove** [grigorii-zander/multi-formik-hook#1]
Hello !

I would love to use this library, but I'm stuck because of another important library in my project that force me to use the Formik `<Formik ...>` element instead of the `useFormik()` hook.

Is there a way to use your library with `<Formik ...>` element ?

I followed your example (https://stackblitz.com/edit/multi-formik-hook-basic-example) and only made change to the `PersonalDataForm` to use `<Formik ...>` element instead.

So I tried this :

```js
const formik = useFormik({
    initialValues,
    validationSchema,
})

return (
    <Formik {...formik}>
        ...
    </Formik>
)
```

When I fill my form, I see the values in the `FormikContext.Provider`, but when I use the `forms.submitAll()` or even the `forms.getValues(instance)` all the values are set the initialValues.

My guess would be that the values in the form stays in the `<Formik ...>` element and aren't accessible from that `formik` variable or something like that.

**Comment by grigorii-zander** [comment]
Hi! Sorry for the late response.
I'm not sure if it's possible to integrate this library with the original `<Formik />` component. It dynamically creates formik hooks (`useFormik`) when you call `bind` or `bindGroup`, which have it's own lifecycle. It's designed to be used as a hook. It triggers validation when some other hook is created or removed from the component tree, or if some form is changed the `dirty` or `valid` state.  Because of this layer of communication between hooks it's not compatible with `<Formik />` component since it has its own lifecycle.
